### ISSUE TITLE
Не работает каллбэк инлайн кнопки! 

### ISSUE THREAD

**Issue by maxobur0001** [TRIGONIM/ggram#3]
Использую GLua. Сервер последней версии игры. Делаю небольшого бота для администрирования сервера. Решил изучить Inline клавиатуры в данном фреймворке, потому скопировал пример с папки examples и удалил idle и require  (то, что требуется для обычного Lua, а не для GLua) . Перезагрузил. Написал /start и нажал на инлайн кнопку, но ничего не произошло. Работает лишь кнопка с ссылкой. Помещал простой print в каллбэк, но в консоли ничего не отправляется. Пожалуйста, помогите! Заранее спасибо =)

**Comment by AMD-NICK** [comment]
Привет. Сейчас еще заканчиваю с рефакторингом и как только доделаю его – сразу проверю в чем дело.

P.S. Я правильно понимаю, что ты ипользуешь этот файл за пример? `examples/inline_keyboard.lua`

И еще несколько вопросов.

1. В консоли сервера при запуске или в процессе работы есть какие-то ошибки, связанные с ggram? 
2. Команда /start работает, но в `bot.callback` не срабатывает принт даже сверху? Т.е. бот вообще не "слышит" ивента callback?

**Comment by maxobur0001** [comment]
> Привет. Сейчас еще заканчиваю с рефакторингом и как только доделаю его – сразу проверю в чем дело.
> 
> P.S. Я правильно понимаю, что ты ипользуешь этот файл за пример? `examples/inline_keyboard.lua`

Да.

**Comment by AMD-NICK** [comment]
Я запустил код из примера в Garry's Mod и в чистом Lua. В обеих случаях пример работает. Возможно, в момент, когда ты скачивал ggram, то я делал какие-то изменения. Попробуй скачай сейчас действительно последнюю версию


<img width="500" src="https://github.com/TRIGONIM/ggram/assets/9200174/a984551e-8bdc-43e6-8ac1-46efa5063f4d">

**Comment by maxobur0001** [comment]
> Я запустил код из примера в Garry's Mod и в чистом Lua. В обеих случаях пример работает. Возможно, в момент, когда ты скачивал ggram, то я делал какие-то изменения. Попробуй скачай сейчас действительно последнюю версию
> 
> 
> <img width="500" src="https://github.com/TRIGONIM/ggram/assets/9200174/a984551e-8bdc-43e6-8ac1-46efa5063f4d">

Хорошо. Спасибо за помощь!

**Comment by AMD-NICK** [comment]
просто для справки. Модуль официально обновлен до версии 2.0

https://github.com/TRIGONIM/ggram/releases/tag/v2.0
